### ISSUE TITLE
VSCP_TYPE_PROTOCOL_START_BLOCK_NACK - Copy&Paste error

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp-doc-spec#11]
VSCP_TYPE_PROTOCOL_START_BLOCK_NACK has the following description part, which is a copy&paste error:

> It is sent by the node as a validation that it can handle the block data transfer.

Just saw its the same for VSCP_TYPE_PROTOCOL_BLOCK_CHUNK_NACK.

**Comment by grodansparadis** [comment]
OK, thanks, fixed in the database, will go to the docs later tonight

No need to implement the chunk responses if one can come up to speed with a transfer anyway. I noticed that  I missed data chunks from time to time and wanted a way to resend them quickly so that is whu I aded them.  One can equally well resend the hole block of course.  But for 8-byte data chunks it feels like that can create a lot of overhead.

**Comment by BlueAndi** [comment]
I started to update vscp-framework and vscp-bootloader to consider the stuff. BTW with the commits of the 28. Nov. I was confused by changing and renaming and rollback and changing ... **LOL**

**Comment by grodansparadis** [comment]
Talk about being confused... LOL   And I did the change and roll back twice... Finally got it at the end I think
