### ISSUE TITLE
CLASS1.ALARM - type 1 first byte - Should be equal to type 2

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp-doc-spec#8]
Should the CLASS1.ALARM type 1 first byte be equal to type 2? Both are different level of conditions.

"Alarm byte from standard register 128/0x80 or a code of choice describing the alarm."

**Comment by grodansparadis** [comment]
Byte 0 is a bit lose in many places. And IMO it is less of a problem then one first think at least if  if one accept that the receiver should know what event(s) it is interested in and therefore also must know the meaning of the data of the event(s) it is interested in.  By design there is nothing in the VSCP specification that state that the should be even a close similarity in the layout of data for a specific event, Even so for some classes, like measurements, it makes sense. 

Why is it a problem as you see it (apart from the obvious that one in some way want to handle all event of a class) with some node/method.

**Comment by BlueAndi** [comment]
Its not a problem, just a question. I just saw your latest changes and thought whether it was forgotten in sense of consistency. Its always easier for the reader to find these similarities. Anway we can keep it as it is, of course.

**Comment by grodansparadis** [comment]
Appreciate that input of course.
